// Sample supplier catalog backing the mock provider. Base values only —
// the mock provider layers deterministic daily drift on top (stock, cost,
// demand), so treat these as "typical" rather than current numbers.

export type CatalogItem = {
  id: string; // supplier product id
  title: string;
  description: string;
  category: string;
  baseCostCents: number;
  baseMarketPriceCents: number;
  shippingCostCents: number;
  baseStock: number;
  baseSalesPerWeek: number;
  baseCompetitorCount: number;
};

export const SUPPLIER_NAME = "MegaSupply (sample data)";

export const CATALOG: CatalogItem[] = [
  // Home & Kitchen
  { id: "MS-1001", title: "Collapsible Silicone Food Storage Containers, Set of 4", description: "Space-saving airtight containers that collapse flat for storage. BPA-free silicone, microwave and dishwasher safe. Set of four sizes from 350ml to 1200ml.", category: "Home & Kitchen", baseCostCents: 612, baseMarketPriceCents: 1899, shippingCostCents: 420, baseStock: 340, baseSalesPerWeek: 41, baseCompetitorCount: 18 },
  { id: "MS-1002", title: "Electric Milk Frother Handheld with Stand", description: "Battery-powered drink mixer for lattes, matcha, and protein shakes. Stainless whisk head, one-button operation, includes counter stand.", category: "Home & Kitchen", baseCostCents: 287, baseMarketPriceCents: 1249, shippingCostCents: 380, baseStock: 520, baseSalesPerWeek: 58, baseCompetitorCount: 44 },
  { id: "MS-1003", title: "Adjustable Rolling Pin with Thickness Rings", description: "Stainless steel rolling pin with four removable thickness discs (2/4/6/10mm) for even dough every time. Great for bakers and cookie decorators.", category: "Home & Kitchen", baseCostCents: 748, baseMarketPriceCents: 2199, shippingCostCents: 520, baseStock: 150, baseSalesPerWeek: 17, baseCompetitorCount: 9 },
  { id: "MS-1004", title: "Under-Cabinet Jar Opener for Weak Hands", description: "Mounts under any cabinet or shelf; grips lids from 0.5 to 4 inches so you can open jars one-handed. Popular with arthritis sufferers and seniors.", category: "Home & Kitchen", baseCostCents: 419, baseMarketPriceCents: 1599, shippingCostCents: 360, baseStock: 275, baseSalesPerWeek: 33, baseCompetitorCount: 12 },
  { id: "MS-1005", title: "Magnetic Spice Rack Organizer for Refrigerator, 4-Tier", description: "Strong magnetic backing holds up to 18 lbs. Moves clutter off counters; includes paper towel bar and hook row. Black powder-coated steel.", category: "Home & Kitchen", baseCostCents: 1130, baseMarketPriceCents: 2999, shippingCostCents: 740, baseStock: 190, baseSalesPerWeek: 26, baseCompetitorCount: 15 },
  { id: "MS-1006", title: "Cold Brew Coffee Maker 1L with Stainless Filter", description: "Borosilicate glass pitcher with ultra-fine mesh filter for smooth cold brew in 12 hours. Airtight lid keeps brew fresh for two weeks.", category: "Home & Kitchen", baseCostCents: 843, baseMarketPriceCents: 2399, shippingCostCents: 610, baseStock: 210, baseSalesPerWeek: 22, baseCompetitorCount: 21 },

  // Pet Supplies
  { id: "MS-2001", title: "Dog Paw Cleaner Cup, Portable Mud Buster - Large", description: "Soft silicone bristles clean muddy paws in seconds — add water, insert paw, twist. Large size for medium and big breeds.", category: "Pet Supplies", baseCostCents: 531, baseMarketPriceCents: 1799, shippingCostCents: 470, baseStock: 410, baseSalesPerWeek: 47, baseCompetitorCount: 23 },
  { id: "MS-2002", title: "Cat Water Fountain 2.5L Ultra-Quiet with LED", description: "Encourages hydration with circulating filtered water. Under 30dB pump, low-water auto shutoff, triple filtration. USB powered.", category: "Pet Supplies", baseCostCents: 962, baseMarketPriceCents: 2599, shippingCostCents: 680, baseStock: 260, baseSalesPerWeek: 38, baseCompetitorCount: 31 },
  { id: "MS-2003", title: "No-Pull Dog Harness with Front Clip, Reflective", description: "Two leash attachment points, padded chest plate, reflective stitching. Four adjustment straps for a escape-proof fit. Sizes S-XL.", category: "Pet Supplies", baseCostCents: 704, baseMarketPriceCents: 2099, shippingCostCents: 450, baseStock: 380, baseSalesPerWeek: 52, baseCompetitorCount: 47 },
  { id: "MS-2004", title: "Interactive Cat Toy - Automatic Rotating Feather Wand", description: "Random-motion feather teaser with three speed modes and auto-off timer. Rechargeable, replacement feathers included.", category: "Pet Supplies", baseCostCents: 617, baseMarketPriceCents: 1899, shippingCostCents: 410, baseStock: 300, baseSalesPerWeek: 29, baseCompetitorCount: 16 },
  { id: "MS-2005", title: "Pet Hair Remover Roller, Reusable Lint Brush", description: "Removes embedded fur from couches, carpets, and car seats with a few strokes. Self-cleaning chamber, no refills ever.", category: "Pet Supplies", baseCostCents: 448, baseMarketPriceCents: 1499, shippingCostCents: 390, baseStock: 620, baseSalesPerWeek: 63, baseCompetitorCount: 38 },
  { id: "MS-2006", title: "Slow Feeder Dog Bowl, Maze Design - Anti-Bloat", description: "Maze ridges slow eating up to 10x to prevent bloat and improve digestion. Non-slip base, food-safe PP, holds 4 cups.", category: "Pet Supplies", baseCostCents: 356, baseMarketPriceCents: 1299, shippingCostCents: 430, baseStock: 450, baseSalesPerWeek: 35, baseCompetitorCount: 27 },

  // Fitness & Outdoors
  { id: "MS-3001", title: "Resistance Bands Set with Door Anchor, 5 Levels", description: "Stackable latex bands from 10 to 50 lbs with handles, ankle straps, door anchor, and carry bag. Full-body home gym in a pouch.", category: "Fitness & Outdoors", baseCostCents: 689, baseMarketPriceCents: 2299, shippingCostCents: 520, baseStock: 340, baseSalesPerWeek: 44, baseCompetitorCount: 52 },
  { id: "MS-3002", title: "Massage Gun Mini, 4 Heads Deep Tissue - Carry Case", description: "Pocket-size percussion massager, 4 speeds, 6-hour battery, under 45dB. Includes four heads and travel case. USB-C charging.", category: "Fitness & Outdoors", baseCostCents: 1725, baseMarketPriceCents: 3999, shippingCostCents: 660, baseStock: 180, baseSalesPerWeek: 31, baseCompetitorCount: 29 },
  { id: "MS-3003", title: "Ab Roller Wheel with Knee Mat and Resistance Bands", description: "Wide non-slip wheel with steel core, ergonomic grips, thick knee pad, and two assist bands for beginners.", category: "Fitness & Outdoors", baseCostCents: 813, baseMarketPriceCents: 2499, shippingCostCents: 590, baseStock: 220, baseSalesPerWeek: 19, baseCompetitorCount: 14 },
  { id: "MS-3004", title: "Insulated Water Bottle 32oz with Straw Lid & Handle", description: "Double-wall stainless keeps drinks cold 24h. Leakproof straw lid, carry handle, fits car cup holders. Powder-coat finish.", category: "Fitness & Outdoors", baseCostCents: 794, baseMarketPriceCents: 2199, shippingCostCents: 640, baseStock: 480, baseSalesPerWeek: 57, baseCompetitorCount: 61 },
  { id: "MS-3005", title: "Camping Lantern Rechargeable, Magnetic Base 1000LM", description: "COB LED lantern with 5 modes, magnetic base, fold-out hook, and power-bank USB out. IPX4, up to 40h on low.", category: "Fitness & Outdoors", baseCostCents: 921, baseMarketPriceCents: 2699, shippingCostCents: 550, baseStock: 240, baseSalesPerWeek: 24, baseCompetitorCount: 17 },
  { id: "MS-3006", title: "Trigger Point Foam Roller 18\" with Exercise Guide", description: "Medium-density EVA roller with ridge pattern for deep-tissue release. Includes printed routine guide. Supports 300 lbs.", category: "Fitness & Outdoors", baseCostCents: 977, baseMarketPriceCents: 2599, shippingCostCents: 780, baseStock: 160, baseSalesPerWeek: 15, baseCompetitorCount: 11 },

  // Electronics Accessories
  { id: "MS-4001", title: "3-in-1 Foldable Wireless Charging Station 15W", description: "Charges phone, earbuds, and smartwatch at once; folds to pocket size for travel. Includes 20W QC adapter and cable.", category: "Electronics", baseCostCents: 1268, baseMarketPriceCents: 3299, shippingCostCents: 480, baseStock: 290, baseSalesPerWeek: 49, baseCompetitorCount: 43 },
  { id: "MS-4002", title: "Car Phone Mount, Military-Grade Suction Dashboard", description: "One-hand operation arm with double-lock suction base that holds through summer heat. Fits 4-7 inch phones with thick cases.", category: "Electronics", baseCostCents: 574, baseMarketPriceCents: 1899, shippingCostCents: 440, baseStock: 510, baseSalesPerWeek: 61, baseCompetitorCount: 56 },
  { id: "MS-4003", title: "USB-C Hub 7-in-1, 4K HDMI 100W PD Aluminum", description: "Adds 4K@60Hz HDMI, three USB 3.0, SD/microSD, and 100W pass-through charging to any USB-C laptop. Plug and play.", category: "Electronics", baseCostCents: 1442, baseMarketPriceCents: 3499, shippingCostCents: 420, baseStock: 230, baseSalesPerWeek: 36, baseCompetitorCount: 34 },
  { id: "MS-4004", title: "Smart LED Strip Lights 32.8ft, App + Remote, Music Sync", description: "RGB strip with app control, mic-driven music sync, timers, and 16M colors. Strong 3M adhesive, cuttable segments.", category: "Electronics", baseCostCents: 856, baseMarketPriceCents: 2499, shippingCostCents: 510, baseStock: 370, baseSalesPerWeek: 43, baseCompetitorCount: 49 },
  { id: "MS-4005", title: "Bluetooth Shower Speaker IPX7 with Suction Cup", description: "Waterproof speaker with punchy bass, 12h battery, and mic for calls. Suction mount plus carabiner loop. Pairs in seconds.", category: "Electronics", baseCostCents: 733, baseMarketPriceCents: 1999, shippingCostCents: 460, baseStock: 320, baseSalesPerWeek: 27, baseCompetitorCount: 25 },
  { id: "MS-4006", title: "Laptop Stand Adjustable Aluminum, Ergonomic Riser", description: "Raises screen up to 7 inches to eye level; solid aluminum with silicone pads holds 22 lbs steady. Folds flat for bags.", category: "Electronics", baseCostCents: 1094, baseMarketPriceCents: 2899, shippingCostCents: 690, baseStock: 200, baseSalesPerWeek: 32, baseCompetitorCount: 28 },

  // Garden & Tools
  { id: "MS-5001", title: "Solar Pathway Lights 8-Pack, Warm White Waterproof", description: "Auto dusk-to-dawn LEDs with 8-10h runtime. Rustproof stakes, IP65. No wiring — install in minutes.", category: "Garden & Tools", baseCostCents: 1387, baseMarketPriceCents: 3599, shippingCostCents: 830, baseStock: 170, baseSalesPerWeek: 28, baseCompetitorCount: 22 },
  { id: "MS-5002", title: "Expandable Garden Hose 50ft with 10-Pattern Nozzle", description: "Triple-latex core expands from 17ft, solid brass fittings, kink-free. Includes spray nozzle and storage bag.", category: "Garden & Tools", baseCostCents: 1176, baseMarketPriceCents: 2999, shippingCostCents: 720, baseStock: 260, baseSalesPerWeek: 34, baseCompetitorCount: 36 },
  { id: "MS-5003", title: "Weeder Tool Stand-Up, 39\" No-Bend Root Remover", description: "Claw grabs weeds by the root with a foot pedal — no kneeling, no chemicals. Steel shaft with ergonomic offset handle.", category: "Garden & Tools", baseCostCents: 924, baseMarketPriceCents: 2799, shippingCostCents: 850, baseStock: 140, baseSalesPerWeek: 21, baseCompetitorCount: 13 },
  { id: "MS-5004", title: "Plant Caddy with Wheels, 14\" Rolling Stand 2-Pack", description: "Move heavy pots without lifting — locking casters, 330 lb capacity each, weatherproof resin deck.", category: "Garden & Tools", baseCostCents: 1043, baseMarketPriceCents: 2699, shippingCostCents: 780, baseStock: 185, baseSalesPerWeek: 18, baseCompetitorCount: 10 },
  { id: "MS-5005", title: "Digital Soil Moisture Meter 4-in-1 for Plants", description: "Reads moisture, pH, light, and temperature with one probe. No batteries needed for moisture mode. Great gift for plant parents.", category: "Garden & Tools", baseCostCents: 498, baseMarketPriceCents: 1699, shippingCostCents: 410, baseStock: 350, baseSalesPerWeek: 25, baseCompetitorCount: 19 },

  // Toys & Games
  { id: "MS-6001", title: "Magnetic Building Tiles 60-Piece STEM Set", description: "Strong-magnet translucent tiles compatible with major brands. Storage bag and idea booklet included. Ages 3+.", category: "Toys & Games", baseCostCents: 1519, baseMarketPriceCents: 3799, shippingCostCents: 760, baseStock: 210, baseSalesPerWeek: 39, baseCompetitorCount: 26 },
  { id: "MS-6002", title: "LCD Writing Tablet 10\" Doodle Board 2-Pack", description: "Pressure-sensitive drawing tablets with one-button erase and screen lock. Six-month battery. Mess-free travel toy.", category: "Toys & Games", baseCostCents: 682, baseMarketPriceCents: 1999, shippingCostCents: 490, baseStock: 400, baseSalesPerWeek: 46, baseCompetitorCount: 33 },
  { id: "MS-6003", title: "Dinosaur Race Track Set 240pc with 4 Dino Cars", description: "Flexible snap-together track builds over 50 layouts. Includes ramp, door, trees, and four dino racers. Ages 3-8.", category: "Toys & Games", baseCostCents: 1234, baseMarketPriceCents: 3299, shippingCostCents: 880, baseStock: 155, baseSalesPerWeek: 23, baseCompetitorCount: 15 },
  { id: "MS-6004", title: "Rocket Launcher Toy, Stomp-Powered 6 Foam Rockets", description: "Kids stomp to launch foam rockets up to 100ft. Adjustable angle, glow-in-dark fins. Backyard hit for ages 4+.", category: "Toys & Games", baseCostCents: 767, baseMarketPriceCents: 2299, shippingCostCents: 640, baseStock: 280, baseSalesPerWeek: 30, baseCompetitorCount: 20 },
  { id: "MS-6005", title: "Water Beads Sensory Kit with Tools, Non-Toxic 50k", description: "Expanding water beads with scoops, tongs, and molds for fine-motor play. Includes mesh bag and storage tub. Ages 3+.", category: "Toys & Games", baseCostCents: 542, baseMarketPriceCents: 1599, shippingCostCents: 470, baseStock: 330, baseSalesPerWeek: 20, baseCompetitorCount: 24 },
];
