import { requireAdmin } from "@/lib/auth";
import { getRainforestEfficiencySummary } from "@/lib/mirror/rainforest";
import { AUTO_PUBLISH_MIN_MARGIN_PCT, AUTO_PUBLISH_MIN_MATCH_CONFIDENCE } from "@/lib/arbitrage/auto-publish";
import { AMAZON_REFRESH_CRON_HOUR, ARBITRAGE_CRON_TIME_ZONE, ARBITRAGE_DAILY_TARGET } from "@/lib/cron/arbitrage-schedule";
import { Badge, Card, PageHeader } from "@/components/ui";

export const metadata = { title: "Admin settings — Sellfinity" };

export default async function AdminSettingsPage() {
  await requireAdmin();
  const rainforest = await getRainforestEfficiencySummary();
  return <div className="space-y-5"><PageHeader title="Admin settings" subtitle="Platform-wide sourcing, publishing, provider, and data-governance rules. Seller pricing preferences are intentionally excluded." />
    <div className="grid gap-5 xl:grid-cols-2">
      <Card className="p-5"><div className="flex items-center justify-between"><h2 className="font-bold text-slate-950">Automated product discovery</h2><Badge tone="green">Enabled</Badge></div><dl className="mt-5 space-y-3 text-sm"><div className="flex justify-between gap-4"><dt className="text-slate-500">Daily opportunity target</dt><dd className="font-semibold">{ARBITRAGE_DAILY_TARGET}</dd></div><div className="flex justify-between gap-4"><dt className="text-slate-500">Amazon refresh</dt><dd className="text-right font-semibold">{AMAZON_REFRESH_CRON_HOUR}:00 · {ARBITRAGE_CRON_TIME_ZONE}</dd></div><div className="flex justify-between gap-4"><dt className="text-slate-500">Arbitrage scan</dt><dd className="text-right font-semibold">03:00 · {ARBITRAGE_CRON_TIME_ZONE}</dd></div></dl><p className="mt-4 text-xs leading-5 text-slate-500">Amazon costs refresh before discovery so published profitability does not rely on stale landed costs.</p></Card>
      <Card className="p-5"><h2 className="font-bold text-slate-950">Publishing quality gates</h2><dl className="mt-5 space-y-3 text-sm"><div className="flex justify-between"><dt className="text-slate-500">Minimum match confidence</dt><dd className="font-semibold">{AUTO_PUBLISH_MIN_MATCH_CONFIDENCE}%</dd></div><div className="flex justify-between"><dt className="text-slate-500">Minimum margin</dt><dd className="font-semibold">{AUTO_PUBLISH_MIN_MARGIN_PCT}%</dd></div><div className="flex justify-between"><dt className="text-slate-500">Shared catalog required</dt><dd><Badge tone="green">Yes</Badge></dd></div><div className="flex justify-between"><dt className="text-slate-500">Seller Rainforest usage</dt><dd><Badge tone="green">Shared cache first</Badge></dd></div></dl></Card>
      <Card className="p-5"><div className="flex items-center justify-between"><h2 className="font-bold text-slate-950">Rainforest provider</h2><Badge tone={rainforest.account ? "green" : "amber"}>{rainforest.account ? "Connected" : "Unavailable"}</Badge></div><dl className="mt-5 grid grid-cols-2 gap-3 text-sm"><div className="rounded-xl bg-slate-50 p-3"><dt className="text-xs text-slate-500">Credits remaining</dt><dd className="mt-1 text-xl font-bold">{rainforest.account?.creditsRemaining?.toLocaleString() ?? "—"}</dd></div><div className="rounded-xl bg-slate-50 p-3"><dt className="text-xs text-slate-500">Paid requests today</dt><dd className="mt-1 text-xl font-bold">{rainforest.providerRequests}</dd></div><div className="rounded-xl bg-emerald-50 p-3"><dt className="text-xs text-emerald-700">Cache saves today</dt><dd className="mt-1 text-xl font-bold text-emerald-800">{rainforest.cacheHits}</dd></div><div className="rounded-xl bg-amber-50 p-3"><dt className="text-xs text-amber-700">Failures today</dt><dd className="mt-1 text-xl font-bold text-amber-800">{rainforest.failures}</dd></div></dl></Card>
      <Card className="p-5"><h2 className="font-bold text-slate-950">Administrative boundaries</h2><div className="mt-4 space-y-3 text-sm leading-5 text-slate-600"><p className="rounded-xl bg-indigo-50 p-3 text-indigo-800">Administrators maintain shared product and market data. Sellers control their own advertising rate, target profit, shipping strategy, listings, and marketplace connections.</p><p className="rounded-xl bg-slate-50 p-3">Seller tools remain available to seller accounts but are no longer mixed into the administrative workspace.</p><p className="rounded-xl bg-slate-50 p-3">All monetary admin reports use finalized eBay earnings and matched Amazon purchase costs when available, with coverage shown wherever estimates remain.</p></div></Card>
    </div>
  </div>;
}
